"""create indexing jobs table

Revision ID: 4484bec1408b
Revises: 4559b903f185
Create Date: 2026-06-14 02:24:26.587148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4484bec1408b'
down_revision: Union[str, Sequence[str], None] = '4559b903f185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexing_jobs_document_id'), 'indexing_jobs', ['document_id'], unique=True)
    op.create_index(op.f('ix_indexing_jobs_id'), 'indexing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_job_id'), 'indexing_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_jobs_job_id'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_id'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_document_id'), table_name='indexing_jobs')
    op.drop_table('indexing_jobs')
    # ### end Alembic commands ###
