"""updated filename and company id columns

Revision ID: 4559b903f185
Revises: 185e3204a86f
Create Date: 2026-06-13 21:16:25.519917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4559b903f185'
down_revision: Union[str, Sequence[str], None] = '185e3204a86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_records', sa.Column('company_id', sa.String(length=255), nullable=False))
    op.drop_column('document_records', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_records', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('document_records', 'company_id')
    # ### end Alembic commands ###
