"""allow multiple document id for indexing

Revision ID: bd9238ecd15c
Revises: 4484bec1408b
Create Date: 2026-06-15 22:32:06.235980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9238ecd15c'
down_revision: Union[str, Sequence[str], None] = '4484bec1408b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_jobs_document_id'), table_name='indexing_jobs')
    op.create_index(op.f('ix_indexing_jobs_document_id'), 'indexing_jobs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_jobs_document_id'), table_name='indexing_jobs')
    op.create_index(op.f('ix_indexing_jobs_document_id'), 'indexing_jobs', ['document_id'], unique=True)
    # ### end Alembic commands ###
